CREATE TABLE IF NOT EXISTS mes_customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_name VARCHAR(255) NOT NULL,
    contact_person VARCHAR(255),
    phone_number VARCHAR(50),
    email VARCHAR(255),
    address TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE mes_customers ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow all access for anon" ON mes_customers;
CREATE POLICY "Allow all access for anon" ON mes_customers FOR ALL USING (true);

-- Gracefully migrate data even if address/email don't exist in mes_operators
DO $$ 
BEGIN 
    BEGIN
        INSERT INTO mes_customers (company_name, contact_person, phone_number, email, address, created_at)
        SELECT name, full_name, phone_number, email, address, created_at
        FROM mes_operators
        WHERE role = 'customer';
    EXCEPTION WHEN undefined_column THEN
        -- If address or email column doesn't exist in mes_operators, fallback
        INSERT INTO mes_customers (company_name, contact_person, phone_number, created_at)
        SELECT name, full_name, phone_number, created_at
        FROM mes_operators
        WHERE role = 'customer';
    END;
END $$;
