CREATE TABLE IF NOT EXISTS mes_customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_name VARCHAR(255) NOT NULL,
    contact_person VARCHAR(255),
    phone_number VARCHAR(50),
    email VARCHAR(255),
    address TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Migrate existing customers from mes_operators to mes_customers
INSERT INTO mes_customers (company_name, contact_person, phone_number, email, address, created_at)
SELECT name, full_name, phone_number, email, address, created_at
FROM mes_operators
WHERE role = 'customer';

-- After successful migration, you can delete them from mes_operators
-- DELETE FROM mes_operators WHERE role = 'customer';
