-- PostgreSQL Schema for Supabase MES

-- Enable UUID extension (useful for Supabase, optional here as we use BIGINT keys)
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. mes_operators
CREATE TABLE mes_operators (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pin_code VARCHAR(4) NOT NULL UNIQUE,
  name VARCHAR(100) NOT NULL,
  role VARCHAR(50) NOT NULL DEFAULT 'employee',
  avatar VARCHAR(10) DEFAULT '',
  color VARCHAR(50) DEFAULT 'bg-slate-500',
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 2. mes_inventory
CREATE TABLE mes_inventory (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  material_name VARCHAR(100) NOT NULL,
  stock_level DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  unit VARCHAR(20) NOT NULL,
  last_updated TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 3. mes_production_logs
CREATE TABLE mes_production_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  operator_id BIGINT REFERENCES mes_operators(id) ON DELETE SET NULL,
  production_week VARCHAR(20) NOT NULL,
  production_date DATE NOT NULL,
  divider_type SMALLINT NOT NULL,
  placement_style VARCHAR(50) NOT NULL,
  size_cm SMALLINT NOT NULL,
  qty_produced INTEGER NOT NULL DEFAULT 0,
  qty_waste INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 4. mes_financial_ledger
CREATE TABLE mes_financial_ledger (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  operator_id BIGINT REFERENCES mes_operators(id) ON DELETE SET NULL,
  target_name VARCHAR(50) NOT NULL DEFAULT '',
  transaction_type VARCHAR(20) NOT NULL,
  amount DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  transaction_date DATE NOT NULL,
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 5. mes_downtime_logs
CREATE TABLE mes_downtime_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  operator_id BIGINT REFERENCES mes_operators(id) ON DELETE SET NULL,
  issue_category VARCHAR(50) NOT NULL,
  start_time TIMESTAMPTZ NOT NULL,
  end_time TIMESTAMPTZ,
  duration_minutes INTEGER,
  resolution_notes TEXT,
  resolved_by VARCHAR(50) DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 6. mes_attendance
CREATE TABLE mes_attendance (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  operator_id BIGINT REFERENCES mes_operators(id) ON DELETE SET NULL,
  production_week VARCHAR(20) NOT NULL,
  shift_date DATE NOT NULL,
  clock_in TIMESTAMPTZ NOT NULL,
  clock_out TIMESTAMPTZ,
  status VARCHAR(50) DEFAULT 'on_time',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 7. mes_loans
CREATE TABLE mes_loans (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  operator_id BIGINT REFERENCES mes_operators(id) ON DELETE SET NULL,
  production_week VARCHAR(20) NOT NULL,
  principal DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  interest_rate DECIMAL(5,2) NOT NULL DEFAULT 0.00,
  status VARCHAR(20) NOT NULL DEFAULT 'active',
  issued_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Row Level Security (RLS) configuration
ALTER TABLE mes_operators ENABLE ROW LEVEL SECURITY;
ALTER TABLE mes_inventory ENABLE ROW LEVEL SECURITY;
ALTER TABLE mes_production_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE mes_financial_ledger ENABLE ROW LEVEL SECURITY;
ALTER TABLE mes_downtime_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE mes_attendance ENABLE ROW LEVEL SECURITY;
ALTER TABLE mes_loans ENABLE ROW LEVEL SECURITY;

-- Allow public access for now (since auth is handled by PINs in the app)
-- In a strict production env, you would issue a custom JWT for each operator
CREATE POLICY "Allow all access for anon" ON mes_operators FOR ALL USING (true);
CREATE POLICY "Allow all access for anon" ON mes_inventory FOR ALL USING (true);
CREATE POLICY "Allow all access for anon" ON mes_production_logs FOR ALL USING (true);
CREATE POLICY "Allow all access for anon" ON mes_financial_ledger FOR ALL USING (true);
CREATE POLICY "Allow all access for anon" ON mes_downtime_logs FOR ALL USING (true);
CREATE POLICY "Allow all access for anon" ON mes_attendance FOR ALL USING (true);
CREATE POLICY "Allow all access for anon" ON mes_loans FOR ALL USING (true);

-- INITIAL SEED DATA
INSERT INTO mes_operators (pin_code, name, role, avatar, color) VALUES
('9999', 'System Admin', 'admin', 'A', 'bg-rose-500'),
('1111', 'Zelalem', 'employee', 'Z', 'bg-indigo-500'),
('2222', 'Aben', 'employee', 'A', 'bg-emerald-500'),
('3333', 'Teme', 'employee', 'T', 'bg-amber-500');
