-- ============================================================
-- MES COMPLETE LATEST MIGRATION SCRIPT
-- Run this in your Supabase SQL Editor (Dashboard -> SQL Editor)
-- ============================================================

-- 1. Ensure mes_inventory has required columns
ALTER TABLE IF EXISTS mes_inventory ADD COLUMN IF NOT EXISTS reorder_threshold DECIMAL(10,2) DEFAULT 15.00;
ALTER TABLE IF EXISTS mes_inventory ADD COLUMN IF NOT EXISTS max_capacity      DECIMAL(10,2) DEFAULT 100.00;

-- 2. Create mes_inventory_logs table for tracking transactions (IN / OUT)
CREATE TABLE IF NOT EXISTS mes_inventory_logs (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    material_id      BIGINT REFERENCES mes_inventory(id) ON DELETE CASCADE,
    transaction_type VARCHAR(10) NOT NULL,
    quantity         DECIMAL(10,2) NOT NULL,
    transaction_date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    notes            TEXT,
    created_at       TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Set Replica Identity to FULL for Realtime change events
ALTER TABLE IF EXISTS mes_attendance REPLICA IDENTITY FULL;
ALTER TABLE IF EXISTS mes_inventory REPLICA IDENTITY FULL;
ALTER TABLE IF EXISTS mes_inventory_logs REPLICA IDENTITY FULL;

-- 4. Enable Row Level Security (RLS) & Policies
ALTER TABLE IF EXISTS mes_inventory ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow all access for anon" ON mes_inventory;
CREATE POLICY "Allow all access for anon" ON mes_inventory FOR ALL USING (true);

ALTER TABLE IF EXISTS mes_inventory_logs ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow all access for anon" ON mes_inventory_logs;
CREATE POLICY "Allow all access for anon" ON mes_inventory_logs FOR ALL USING (true);

ALTER TABLE IF EXISTS mes_attendance ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow all access for anon" ON mes_attendance;
CREATE POLICY "Allow all access for anon" ON mes_attendance FOR ALL USING (true);

-- 5. Enable Supabase Realtime Publication for instant cross-device live sync
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables 
    WHERE pubname = 'supabase_realtime' AND tablename = 'mes_inventory'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE mes_inventory;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables 
    WHERE pubname = 'supabase_realtime' AND tablename = 'mes_inventory_logs'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE mes_inventory_logs;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables 
    WHERE pubname = 'supabase_realtime' AND tablename = 'mes_attendance'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE mes_attendance;
  END IF;
END $$;

-- 6. Seed default inventory materials if table is empty
INSERT INTO mes_inventory (material_name, stock_level, unit, reorder_threshold, max_capacity)
VALUES
    ('Wire',       0, 'kg',      15, 100),
    ('Chaf',       0, 'kg',      15, 100),
    ('Shibo',      0, 'rolls',   15, 100),
    ('Plaster',    0, 'bags',    15, 100),
    ('Paper',      0, 'rolls',   15, 100),
    ('FuseLead',   0, 'kg',      15, 100),
    ('Cm',         0, 'kg',      15, 100),
    ('GlueStucko', 0, 'buckets', 15, 100)
ON CONFLICT DO NOTHING;
