-- ============================================================
-- MES Supabase Migration: QC Defects + Inventory Extensions
-- Run this in your Supabase SQL Editor
-- ============================================================

-- 1. QC Defects table
CREATE TABLE IF NOT EXISTS mes_qc_defects (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operator_id     BIGINT REFERENCES mes_operators(id) ON DELETE SET NULL,
    machine_id      BIGINT,
    divider_type    VARCHAR(20),
    category        VARCHAR(50)  NOT NULL,
    quantity        INTEGER      NOT NULL DEFAULT 0,
    production_week VARCHAR(20)  NOT NULL,
    logged_at       TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

ALTER TABLE mes_qc_defects ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow all access for anon" ON mes_qc_defects;
CREATE POLICY "Allow all access for anon" ON mes_qc_defects FOR ALL USING (true);

-- Enable Realtime for QC defects (so all tablets see new defects instantly)
ALTER PUBLICATION supabase_realtime ADD TABLE mes_qc_defects;

-- 2. Extend mes_inventory with reorder_threshold and max_capacity columns
ALTER TABLE mes_inventory ADD COLUMN IF NOT EXISTS reorder_threshold DECIMAL(10,2) DEFAULT 15;
ALTER TABLE mes_inventory ADD COLUMN IF NOT EXISTS max_capacity      DECIMAL(10,2) DEFAULT 200;

-- 3. Seed default inventory materials (safe to re-run — skips on conflict)
ALTER TABLE mes_inventory DROP CONSTRAINT IF EXISTS mes_inventory_material_name_unique;
ALTER TABLE mes_inventory ADD CONSTRAINT mes_inventory_material_name_unique UNIQUE (material_name);

INSERT INTO mes_inventory (material_name, stock_level, unit, reorder_threshold, max_capacity)
VALUES
    ('Standard Sheet Metal',  50,  'm2',  15, 200),
    ('Premium Coating Paint', 120, 'L',   40, 500),
    ('Industrial Lubricant',  10,  'gal', 15, 50 )
ON CONFLICT (material_name) DO NOTHING;

-- Enable RLS on inventory (already in original schema, ensuring policy exists)
DROP POLICY IF EXISTS "Allow all access for anon" ON mes_inventory;
CREATE POLICY "Allow all access for anon" ON mes_inventory FOR ALL USING (true);

-- 4. Add production_week column to mes_downtime_logs if not present
ALTER TABLE mes_downtime_logs ADD COLUMN IF NOT EXISTS production_week VARCHAR(20);

-- Enable Realtime for downtime logs (cross-tablet downtime alerts)
ALTER PUBLICATION supabase_realtime ADD TABLE mes_downtime_logs;

-- ============================================================
-- Done! Run the above once in Supabase SQL Editor.
-- ============================================================
